# save model

In [19]:
import numpy as np
import tensorflow as tf
x_train = np.random.random((1000, 32))
y_train = np.random.randint(10, size=(1000,))
x_val = np.random.random((200, 32))
y_val = np.random.randint(10, size=(200,))
x_test = np.random.random((200, 32))
y_test = np.random.randint(10, size=(200,))

In [20]:
def get_uncompiled_model():
    inputs = tf.keras.Input(shape=(32,), name='digits',dtype=tf.float16)
    x = tf.keras.layers.Dense(64, activation='relu', name='dense_1', dtype=tf.float16)(inputs)
    x = tf.keras.layers.Dense(64, activation='relu', name='dense_2',dtype=tf.float16)(x)
    outputs = tf.keras.layers.Dense(10, name='predictions',dtype=tf.float16)(x)
    model = tf.keras.Model(inputs=inputs, outputs=outputs)
    return model

def get_compiled_model():
    model = get_uncompiled_model()
    model.compile(optimizer=tf.keras.optimizers.RMSprop(learning_rate=1e-3),
                 loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
                 metrics=['sparse_categorical_accuracy'])
    return model

In [21]:
model = get_compiled_model()

In [22]:
model.fit(x_train, y_train, batch_size=32, epochs=5, validation_data=(x_val, y_val))

Epoch 1/5
32/32 [==============================] - 0s 13ms/step - loss: 49.4333 - sparse_categorical_accuracy: 0.0980 - val_loss: 36.8625 - val_sparse_categorical_accuracy: 0.0600
Epoch 2/5
32/32 [==============================] - 0s 10ms/step - loss: 28.9548 - sparse_categorical_accuracy: 0.1020 - val_loss: 22.7606 - val_sparse_categorical_accuracy: 0.0900
Epoch 3/5
32/32 [==============================] - 0s 10ms/step - loss: 20.4050 - sparse_categorical_accuracy: 0.0940 - val_loss: 17.8025 - val_sparse_categorical_accuracy: 0.0850
Epoch 4/5
32/32 [==============================] - 0s 10ms/step - loss: 15.6937 - sparse_categorical_accuracy: 0.0940 - val_loss: 13.8681 - val_sparse_categorical_accuracy: 0.1000
Epoch 5/5
32/32 [==============================] - 0s 11ms/step - loss: 12.1441 - sparse_categorical_accuracy: 0.0980 - val_loss: 11.2909 - val_sparse_categorical_accuracy: 0.1100


In [23]:
model.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
digits (InputLayer)          [(None, 32)]              0         
_________________________________________________________________
dense_1 (Dense)              (None, 64)                2112      
_________________________________________________________________
dense_2 (Dense)              (None, 64)                4160      
_________________________________________________________________
predictions (Dense)          (None, 10)                650       
Total params: 6,922
Trainable params: 6,922
Non-trainable params: 0
_________________________________________________________________


## save weights

In [7]:
model.save_weights("drrp.h5")

In [8]:
model.load_weights("drrp.h5")

In [9]:
model.predict(x_test)

array([[ -27.78,  -83.4 ,  -47.7 , ...,  -73.5 ,  -28.86,  -38.4 ],
       [ -65.7 ,  -97.94,  -70.44, ...,  -98.2 ,  -53.8 ,  -51.56],
       [ -32.3 ,  -78.5 ,  -34.56, ...,  -33.56,  -37.97,  -39.97],
       ...,
       [ -69.2 ,  -73.4 ,  -62.8 , ..., -105.06,  -67.7 ,  -73.94],
       [ -41.3 ,  -43.53,  -43.9 , ...,  -28.58,  -33.03,  -37.06],
       [ -37.56, -103.2 ,  -54.38, ...,  -75.2 ,  -84.9 ,  -43.22]],
      dtype=float16)

In [10]:
# checkpoints
model.save_weights('./checkpoints/mannul_checkpoint')
model.load_weights('./checkpoints/mannul_checkpoint')
model.predict(x_test)

array([[ -27.78,  -83.4 ,  -47.7 , ...,  -73.5 ,  -28.86,  -38.4 ],
       [ -65.7 ,  -97.94,  -70.44, ...,  -98.2 ,  -53.8 ,  -51.56],
       [ -32.3 ,  -78.5 ,  -34.56, ...,  -33.56,  -37.97,  -39.97],
       ...,
       [ -69.2 ,  -73.4 ,  -62.8 , ..., -105.06,  -67.7 ,  -73.94],
       [ -41.3 ,  -43.53,  -43.9 , ...,  -28.58,  -33.03,  -37.06],
       [ -37.56, -103.2 ,  -54.38, ...,  -75.2 ,  -84.9 ,  -43.22]],
      dtype=float16)

## Save Keras model

In [11]:
model.save('path_to_my_model.h5')

new_model = tf.keras.models.load_model('path_to_my_model.h5')
new_model.predict(x_test)

array([[ -27.78,  -83.4 ,  -47.7 , ...,  -73.5 ,  -28.86,  -38.4 ],
       [ -65.7 ,  -97.94,  -70.44, ...,  -98.2 ,  -53.8 ,  -51.56],
       [ -32.3 ,  -78.5 ,  -34.56, ...,  -33.56,  -37.97,  -39.97],
       ...,
       [ -69.2 ,  -73.4 ,  -62.8 , ..., -105.06,  -67.7 ,  -73.94],
       [ -41.3 ,  -43.53,  -43.9 , ...,  -28.58,  -33.03,  -37.06],
       [ -37.56, -103.2 ,  -54.38, ...,  -75.2 ,  -84.9 ,  -43.22]],
      dtype=float16)

In [12]:
import pyScoring

Loaded scoring jar from /Users/fatu/venv/tensorflow2py37/jars/scoring-all-in-one.jar


## Save tensorflow format

In [13]:
model.save('path_to_saved_model', save_format='tf')

new_model = tf.keras.models.load_model('path_to_saved_model')
new_model.predict(x_test)

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
INFO:tensorflow:Assets written to: path_to_saved_model/assets


array([[ -27.78,  -83.4 ,  -47.7 , ...,  -73.5 ,  -28.86,  -38.4 ],
       [ -65.7 ,  -97.94,  -70.44, ...,  -98.2 ,  -53.8 ,  -51.56],
       [ -32.3 ,  -78.5 ,  -34.56, ...,  -33.56,  -37.97,  -39.97],
       ...,
       [ -69.2 ,  -73.4 ,  -62.8 , ..., -105.06,  -67.7 ,  -73.94],
       [ -41.3 ,  -43.53,  -43.9 , ...,  -28.58,  -33.03,  -37.06],
       [ -37.56, -103.2 ,  -54.38, ...,  -75.2 ,  -84.9 ,  -43.22]],
      dtype=float16)

In [14]:
tf.saved_model.save(model, 'my_saved_model')
restored_saved_model = tf.saved_model.load('my_saved_model')
f = restored_saved_model.signatures["serving_default"]

INFO:tensorflow:Assets written to: my_saved_model/assets


In [15]:
!source ~/venv/tensorflow2py37/bin/activate && python /Users/fatu/venv/tensorflow1.5/bin/saved_model_cli show --dir my_saved_model --all


MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:

signature_def['__saved_model_init_op']:
  The given SavedModel SignatureDef contains the following input(s):
  The given SavedModel SignatureDef contains the following output(s):
    outputs['__saved_model_init_op'] tensor_info:
        dtype: DT_INVALID
        shape: unknown_rank
        name: NoOp
  Method name is: 

signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['digits'] tensor_info:
        dtype: DT_HALF
        shape: (-1, 32)
        name: serving_default_digits:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['predictions'] tensor_info:
        dtype: DT_HALF
        shape: (-1, 10)
        name: StatefulPartitionedCall:0
  Method name is: tensorflow/serving/predict
Instructions for updating:
If using Keras pass *_constraint arguments to layers.

Defined Functions:
  Function Name: '__call__'
    Optio

In [16]:
!tree path_to_saved_model

path_to_saved_model
├── assets
├── saved_model.pb
└── variables
    ├── variables.data-00000-of-00001
    └── variables.index

2 directories, 3 files


In [17]:
from pyScoring import ModelCreator

In [24]:
test = ModelCreator("test")

In [25]:
test.addKerasModel(model)

The input is empty, we will try to imply the input size
find model input size is 32 flatten the input...
generated input ['c0', 'c1', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7', 'c8', 'c9', 'c10', 'c11', 'c12', 'c13', 'c14', 'c15', 'c16', 'c17', 'c18', 'c19', 'c20', 'c21', 'c22', 'c23', 'c24', 'c25', 'c26', 'c27', 'c28', 'c29', 'c30', 'c31']
Num_of_layers= 4
In layer # -1


KeyError: 'digits'

In [26]:
help(test)

Help on ModelCreator in module pyScoring.smart_model_builder object:

class ModelCreator(builtins.object)
 |  ModelCreator(name: str = '')
 |  
 |  Methods defined here:
 |  
 |  __init__(self, name: str = '')
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  addH2OTransforms(self, name_of_modelConfig: str, path_to_modelConfig: str) -> str
 |      Add H2O MOJO file transformation
 |  
 |  addKerasModel(self, model, inputs: list = None, outputs: list = None, implenmentation=0) -> None
 |      Add model built from Keras
 |      
 |      Args:
 |          model: A model from Keras
 |          inputs: the input variables, if the inputs is None, all the input 
 |                  variables will generated, e.g. if the model have multiple inputs, 
 |                  each inputs will have a prefix k, and const charactor 'c', append another index for the ith features
 |                  e.g. [[0c0, 0c1, 0c2, 0c3, ...], [1c0, 1c1, 1c2,...]...]  
 |                 