# Keras 模型保存与加载

In [4]:
import numpy as np
import tensorflow as tf
x_train = np.random.random((1000, 32))
y_train = np.random.randint(10, size=(1000,))
x_val = np.random.random((200, 32))
y_val = np.random.randint(10, size=(200,))
x_test = np.random.random((200, 32))
y_test = np.random.randint(10, size=(200,))

In [5]:
def get_uncompiled_model():
    inputs = tf.keras.Input(shape=(32,), name='digits',dtype=tf.float16)
    x = tf.keras.layers.Dense(64, activation='relu', name='dense_1', dtype=tf.float16)(inputs)
    x = tf.keras.layers.Dense(64, activation='relu', name='dense_2',dtype=tf.float16)(x)
    outputs = tf.keras.layers.Dense(10, name='predictions',dtype=tf.float16)(x)
    model = tf.keras.Model(inputs=inputs, outputs=outputs)
    return model

def get_compiled_model():
    model = get_uncompiled_model()
    model.compile(optimizer=tf.keras.optimizers.RMSprop(learning_rate=1e-3),
                 loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
                 metrics=['sparse_categorical_accuracy'])
    return model

In [6]:
model = get_compiled_model()

In [7]:
model.fit(x_train, y_train, batch_size=32, epochs=5, validation_data=(x_val, y_val))

Epoch 1/5
32/32 [==============================] - 0s 13ms/step - loss: 41.3672 - sparse_categorical_accuracy: 0.1060 - val_loss: 27.4319 - val_sparse_categorical_accuracy: 0.1100
Epoch 2/5
32/32 [==============================] - 0s 8ms/step - loss: 24.2849 - sparse_categorical_accuracy: 0.1090 - val_loss: 19.0575 - val_sparse_categorical_accuracy: 0.0850
Epoch 3/5
32/32 [==============================] - 0s 8ms/step - loss: 19.3415 - sparse_categorical_accuracy: 0.1030 - val_loss: 16.4742 - val_sparse_categorical_accuracy: 0.1050
Epoch 4/5
32/32 [==============================] - 0s 8ms/step - loss: 17.3769 - sparse_categorical_accuracy: 0.1050 - val_loss: 14.6544 - val_sparse_categorical_accuracy: 0.1050
Epoch 5/5
32/32 [==============================] - 0s 8ms/step - loss: 15.8088 - sparse_categorical_accuracy: 0.1060 - val_loss: 13.6214 - val_sparse_categorical_accuracy: 0.0950


In [8]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
digits (InputLayer)          [(None, 32)]              0         
_________________________________________________________________
dense_1 (Dense)              (None, 64)                2112      
_________________________________________________________________
dense_2 (Dense)              (None, 64)                4160      
_________________________________________________________________
predictions (Dense)          (None, 10)                650       
Total params: 6,922
Trainable params: 6,922
Non-trainable params: 0
_________________________________________________________________


## 方法一 save_weights

In [25]:
model.save_weights("drrp.h5")

In [23]:
model.load_weights("drrp.h5")

In [24]:
model.predict(x_test)

array([[ 0.05852645,  0.01292044, -0.23259905, ..., -0.10551147,
        -0.00613356,  0.16358103],
       [-0.06289405, -0.1480409 ,  0.36335117, ...,  0.15499479,
         0.00501488, -0.12265167],
       [ 0.00436173,  0.01297364, -0.13949364, ..., -0.14975196,
        -0.16100915,  0.132042  ],
       ...,
       [-0.18670836, -0.0823878 , -0.2774019 , ..., -0.19423302,
        -0.12751162,  0.28515926],
       [-0.07826158, -0.36988124, -0.34250683, ...,  0.0766313 ,
        -0.21119668,  0.2753719 ],
       [ 0.01388641, -0.12932897, -0.04209207, ...,  0.03581356,
         0.01053141,  0.1093277 ]], dtype=float32)

In [25]:
# checkpoints
model.save_weights('./checkpoints/mannul_checkpoint')
model.load_weights('./checkpoints/mannul_checkpoint')
model.predict(x_test)

array([[ 0.05852645,  0.01292044, -0.23259905, ..., -0.10551147,
        -0.00613356,  0.16358103],
       [-0.06289405, -0.1480409 ,  0.36335117, ...,  0.15499479,
         0.00501488, -0.12265167],
       [ 0.00436173,  0.01297364, -0.13949364, ..., -0.14975196,
        -0.16100915,  0.132042  ],
       ...,
       [-0.18670836, -0.0823878 , -0.2774019 , ..., -0.19423302,
        -0.12751162,  0.28515926],
       [-0.07826158, -0.36988124, -0.34250683, ...,  0.0766313 ,
        -0.21119668,  0.2753719 ],
       [ 0.01388641, -0.12932897, -0.04209207, ...,  0.03581356,
         0.01053141,  0.1093277 ]], dtype=float32)

## 方法二 整个模型

In [6]:
model.save('path_to_saved_model', save_format='tf')

new_model = tf.keras.models.load_model('path_to_saved_model')
new_model.predict(x_test)

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
INFO:tensorflow:Assets written to: path_to_saved_model/assets


array([[-0.00409392, -0.00313468, -0.08112855, ..., -0.06384258,
        -0.14178936, -0.00161422],
       [ 0.12763125, -0.26022148,  0.04546265, ...,  0.06015725,
        -0.1318432 , -0.06218194],
       [ 0.09995539,  0.03873311,  0.3017472 , ..., -0.32389206,
         0.0159488 , -0.07385943],
       ...,
       [ 0.07943917, -0.26608714,  0.09972487, ...,  0.07722213,
        -0.11452483,  0.00932745],
       [ 0.06275637,  0.27457577, -0.01840128, ...,  0.10620368,
         0.1495491 , -0.12419467],
       [ 0.11535957, -0.01981927,  0.0197123 , ...,  0.05708698,
         0.04515108, -0.07603381]], dtype=float32)

## 方法三

In [28]:
model.save('path_to_my_model.h5')

new_model = tf.keras.models.load_model('path_to_my_model.h5')
new_model.predict(x_test)

array([[ 0.05852645,  0.01292044, -0.23259905, ..., -0.10551147,
        -0.00613356,  0.16358103],
       [-0.06289405, -0.1480409 ,  0.36335117, ...,  0.15499479,
         0.00501488, -0.12265167],
       [ 0.00436173,  0.01297364, -0.13949364, ..., -0.14975196,
        -0.16100915,  0.132042  ],
       ...,
       [-0.18670836, -0.0823878 , -0.2774019 , ..., -0.19423302,
        -0.12751162,  0.28515926],
       [-0.07826158, -0.36988124, -0.34250683, ...,  0.0766313 ,
        -0.21119668,  0.2753719 ],
       [ 0.01388641, -0.12932897, -0.04209207, ...,  0.03581356,
         0.01053141,  0.1093277 ]], dtype=float32)

## 方法四

In [29]:
tf.saved_model.save(model, 'my_saved_model')
restored_saved_model = tf.saved_model.load('my_saved_model')
f = restored_saved_model.signatures["serving_default"]

INFO:tensorflow:Assets written to: my_saved_model/assets


In [30]:
f(digits = tf.constant(x_test.tolist()))

{'predictions': <tf.Tensor: shape=(200, 10), dtype=float32, numpy=
 array([[ 0.05852645,  0.01292044, -0.23259905, ..., -0.10551147,
         -0.00613356,  0.16358103],
        [-0.06289405, -0.1480409 ,  0.36335117, ...,  0.15499479,
          0.00501488, -0.12265167],
        [ 0.00436173,  0.01297364, -0.13949364, ..., -0.14975196,
         -0.16100915,  0.132042  ],
        ...,
        [-0.18670836, -0.0823878 , -0.2774019 , ..., -0.19423302,
         -0.12751162,  0.28515926],
        [-0.07826155, -0.36988118, -0.3425069 , ...,  0.07663134,
         -0.21119669,  0.27537188],
        [ 0.01388641, -0.12932895, -0.04209203, ...,  0.03581361,
          0.01053139,  0.10932764]], dtype=float32)>}

# 自定义版本模型保存与加载

In [43]:
import numpy as np
class MyModel(tf.keras.Model):
    def __init__(self, num_classes=10):
        super(MyModel, self).__init__(name='my_model')
        self.num_classes = num_classes
        self.dense_1 = tf.keras.layers.Dense(32, activation='relu')
        self.dense_2 = tf.keras.layers.Dense(num_classes)
            
    @tf.function(input_signature=[tf.TensorSpec([None, 32], tf.float32)])
    def call(self, inputs):
        x = self.dense_1(inputs)
        return self.dense_2(x)

In [44]:
import numpy as np

x_train = np.random.random((1000, 32))
y_train = np.random.randint(10, size=(1000,))
x_val = np.random.random((200, 32))
y_val = np.random.randint(10, size=(200,))
x_test = np.random.random((200, 32))
y_test = np.random.randint(10, size=(200,))


optimizer = tf.keras.optimizers.SGD(learning_rate=1e-3)

loss_fn = tf.keras.losses.CategoricalCrossentropy(from_logits=True)

train_acc_metric = tf.keras.metrics.CategoricalAccuracy()
val_acc_metric = tf.keras.metrics.CategoricalAccuracy()

batch_size = 64
train_dataset = tf.data.Dataset.from_tensor_slices((data, labels))
train_dataset = train_dataset.shuffle(buffer_size=1024).batch(batch_size)

val_dataset = tf.data.Dataset.from_tensor_slices((x_val, y_val))
val_dataset = val_dataset.batch(batch_size)

In [45]:
model = MyModel(num_classes=10)
epochs = 3
for epoch in range(epochs):
    print('Start of epoch %d' % (epoch,))
    
    for step, (x_batch_train, y_batch_train) in enumerate(train_dataset):
        
        with tf.GradientTape() as tape:
            
            logits = model(x_batch_train, training=True)
            
            loss_value = loss_fn(y_batch_train, logits)
            
        grads = tape.gradient(loss_value, model.trainable_weights)
        
        optimizer.apply_gradients(zip(grads, model.trainable_weights))
        
        train_acc_metric(y_batch_train, logits)
        
        if step % 200 == 0:
            print('Training loss (for one batch) at step %s: %s' % (step, float(loss_value)))
            print('Seen so far: %s samples' % ((step + 1) * 64))
            
    train_acc = train_acc_metric.result()
    print('Training acc over epoch: %s' % (float(train_acc),))
    
    train_acc_metric.reset_states()
    
    for x_batch_val, y_batch_val in val_dataset:
        val_logits = model(x_batch_val)
        
        val_acc_metric(y_batch_val, val_logits)
        
    val_acc = val_acc_metric.result()
    val_acc_metric.reset_states()
    print('Validation acc: %s' % (float(val_acc),))

Start of epoch 0

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

Training loss (for one batch) at step 0: 12.215283393859863
Seen so far: 64 samples
Training acc over epoch: 0.09799999743700027
Validation acc: 0.029999999329447746
Start of epoch 1
Training loss (for one batch) at step 0: 11.870205879211426
Seen so far: 64 samples
Training acc over epoch: 0.10100000351667404
Validation acc: 0.019999999552965164
Start of epoch 2
Training loss (for one batch) at step 0: 11.69017219543457
Seen so far: 64 samples
Training acc over epoch: 0.101000003516674

## 模型保存方法一

In [46]:
model.save_weights("drrp.h5")
model.load_weights("drrp.h5")
model.predict(x_test)

array([[ 0.23457022,  0.6700156 ,  0.98961985, ...,  1.0819362 ,
         0.2749272 ,  0.8553397 ],
       [ 0.46010363,  0.5857373 ,  0.9385505 , ...,  0.7562412 ,
         0.6000906 ,  0.47855237],
       [ 0.35790527,  0.45883706,  1.5235121 , ...,  0.49148226,
        -0.15018994,  1.312606  ],
       ...,
       [ 0.7966254 ,  0.7490465 ,  0.97471374, ...,  0.5026726 ,
         0.04536883,  0.6334813 ],
       [ 0.11808767,  0.6573901 ,  0.71505857, ...,  0.7634459 ,
         0.30052808,  0.32086703],
       [ 0.10565991,  0.4186309 ,  0.86704206, ...,  0.8332339 ,
         0.34078637,  0.52047175]], dtype=float32)

In [47]:
# checkpoints
model.save_weights('./checkpoints/mannul_checkpoint')
model.load_weights('./checkpoints/mannul_checkpoint')
model.predict(x_test)

array([[ 0.23457022,  0.6700156 ,  0.98961985, ...,  1.0819362 ,
         0.2749272 ,  0.8553397 ],
       [ 0.46010363,  0.5857373 ,  0.9385505 , ...,  0.7562412 ,
         0.6000906 ,  0.47855237],
       [ 0.35790527,  0.45883706,  1.5235121 , ...,  0.49148226,
        -0.15018994,  1.312606  ],
       ...,
       [ 0.7966254 ,  0.7490465 ,  0.97471374, ...,  0.5026726 ,
         0.04536883,  0.6334813 ],
       [ 0.11808767,  0.6573901 ,  0.71505857, ...,  0.7634459 ,
         0.30052808,  0.32086703],
       [ 0.10565991,  0.4186309 ,  0.86704206, ...,  0.8332339 ,
         0.34078637,  0.52047175]], dtype=float32)

## 模型保存方法二

In [49]:
# 不能保存H5
model.save('path_to_my_model')

new_model = tf.keras.models.load_model('path_to_my_model')
new_model.predict(x_test)

INFO:tensorflow:Assets written to: path_to_my_model/assets


array([[ 0.23457022,  0.6700156 ,  0.98961985, ...,  1.0819362 ,
         0.2749272 ,  0.8553397 ],
       [ 0.46010363,  0.5857373 ,  0.9385505 , ...,  0.7562412 ,
         0.6000906 ,  0.47855237],
       [ 0.35790527,  0.45883706,  1.5235121 , ...,  0.49148226,
        -0.15018994,  1.312606  ],
       ...,
       [ 0.7966254 ,  0.7490465 ,  0.97471374, ...,  0.5026726 ,
         0.04536883,  0.6334813 ],
       [ 0.11808767,  0.6573901 ,  0.71505857, ...,  0.7634459 ,
         0.30052808,  0.32086703],
       [ 0.10565991,  0.4186309 ,  0.86704206, ...,  0.8332339 ,
         0.34078637,  0.52047175]], dtype=float32)

## 方法四

In [54]:
tf.saved_model.save(model, 'my_saved_model')
restored_saved_model = tf.saved_model.load('my_saved_model')
f = restored_saved_model.signatures["serving_default"]

INFO:tensorflow:Assets written to: my_saved_model/assets


In [56]:
f(args_0 = tf.constant(x_test.tolist()))

{'output_1': <tf.Tensor: shape=(200, 10), dtype=float32, numpy=
 array([[ 0.23457022,  0.6700156 ,  0.98961985, ...,  1.0819362 ,
          0.2749272 ,  0.8553397 ],
        [ 0.46010363,  0.5857373 ,  0.9385505 , ...,  0.7562412 ,
          0.6000906 ,  0.47855237],
        [ 0.35790527,  0.45883706,  1.5235121 , ...,  0.49148226,
         -0.15018994,  1.312606  ],
        ...,
        [ 0.7966254 ,  0.7490465 ,  0.97471374, ...,  0.5026726 ,
          0.04536883,  0.6334813 ],
        [ 0.11808767,  0.6573901 ,  0.71505857, ...,  0.7634459 ,
          0.30052808,  0.32086703],
        [ 0.10565991,  0.4186309 ,  0.86704206, ...,  0.8332339 ,
          0.34078637,  0.52047175]], dtype=float32)>}