In [3]:
import tensorflow as tf
print(tf.__version__)

2.2.0


In [2]:
print(tf.test.is_gpu_available())

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
False


# 张量

In [4]:
# Rank 0
mammal=tf.Variable("Elephant", tf.string)
tf.print(tf.rank(mammal))
tf.print(tf.shape(mammal))

0
[]


In [5]:
print(tf.rank(mammal))

tf.Tensor(0, shape=(), dtype=int32)


In [6]:
# Rank 1
mystr=tf.Variable(["Hello"], tf.string)
tf.print(tf.rank(mystr))
tf.print(tf.shape(mystr))

1
[1]


In [7]:
# Rank 2
mymat = tf.Variable([[7],[11]], tf.int16)
tf.print(tf.rank(mymat))
tf.print(tf.shape(mymat))

2
[2 1]


### 创建张量

In [8]:
tf.constant([1,2,3],dtype=tf.int16)

<tf.Tensor: shape=(3,), dtype=int16, numpy=array([1, 2, 3], dtype=int16)>

* tf.strings
* tf.debugging
* tf.dtypes
* tf.math
* tf.random
* tf.feature_column

https://www.tensorflow.org/tutorials/structured_data/feature_columns

In [9]:
tf.strings.bytes_split('hello')

<tf.Tensor: shape=(5,), dtype=string, numpy=array([b'h', b'e', b'l', b'l', b'o'], dtype=object)>

In [10]:
tf.strings.split('hello world')

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'hello', b'world'], dtype=object)>

In [11]:
tf.strings.to_hash_bucket(['hello','world'], num_buckets=10)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([8, 1])>

In [12]:
a = tf.random.uniform((10,10))
tf.debugging.assert_equal(x=a.shape,y=(10,10))

In [13]:
tf.debugging.assert_equal(x=a.shape,y=(10,11))

InvalidArgumentError: Condition x == y did not hold.
Indices of first 1 different values:
[[1]]
Corresponding x values:
[10]
Corresponding y values:
[11]
First 2 elements of x:
[10 10]
First 2 elements of y:
[10 11]

In [16]:
a = tf.random.uniform(shape=(10,5), minval=0, maxval=10)
a

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[0.1557672 , 2.2525835 , 8.16264   , 1.686424  , 7.8550234 ],
       [9.53514   , 9.0258465 , 0.12324214, 0.69693327, 0.9070194 ],
       [3.5409963 , 6.9560566 , 0.53347707, 6.8186245 , 1.5968692 ],
       [1.0213435 , 8.323487  , 9.980812  , 1.498003  , 4.164954  ],
       [2.2006404 , 4.793543  , 4.801813  , 8.555811  , 3.2682538 ],
       [8.869379  , 2.4322116 , 7.0849276 , 9.897023  , 3.4844756 ],
       [2.9485476 , 7.231443  , 8.365526  , 0.35217404, 1.9879568 ],
       [1.4192426 , 4.7125587 , 3.3494806 , 8.137943  , 9.895683  ],
       [7.2306347 , 3.854189  , 3.84071   , 0.8859801 , 6.324477  ],
       [4.9630775 , 0.39732456, 4.836247  , 2.4690366 , 8.885965  ]],
      dtype=float32)>

In [15]:
tf.math.add(a,a)

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[2.92079926e+00, 1.32604313e+01, 1.20524502e+01, 5.24496555e+00,
        1.69800568e+01],
       [7.52382755e+00, 1.84345245e-02, 1.48055506e+01, 7.25996733e+00,
        1.29975052e+01],
       [1.93547249e+00, 3.25128555e+00, 7.60039091e+00, 1.32329464e-01,
        1.94241333e+01],
       [1.02106810e+01, 9.19758606e+00, 1.72485332e+01, 1.18843079e+00,
        1.65904808e+01],
       [1.82590065e+01, 7.77758598e+00, 1.98067513e+01, 1.88941479e+00,
        1.29044342e+01],
       [1.60315037e-01, 5.29584885e-01, 1.72188997e+00, 6.70494556e+00,
        1.56496048e+00],
       [1.69570236e+01, 7.11362600e+00, 8.07301712e+00, 4.18546200e+00,
        3.60766411e+00],
       [5.47444820e+00, 6.94928885e+00, 1.05107355e+01, 1.56078453e+01,
        1.86358032e+01],
       [1.34274406e+01, 1.86947327e+01, 7.64301777e+00, 1.06642532e+01,
        1.80764008e+01],
       [1.60887184e+01, 6.62447453e+00, 5.66275597e+00, 7.22794056e+00,
      

In [17]:
tf.dtypes.cast(a, tf.int32)

<tf.Tensor: shape=(10, 5), dtype=int32, numpy=
array([[0, 2, 8, 1, 7],
       [9, 9, 0, 0, 0],
       [3, 6, 0, 6, 1],
       [1, 8, 9, 1, 4],
       [2, 4, 4, 8, 3],
       [8, 2, 7, 9, 3],
       [2, 7, 8, 0, 1],
       [1, 4, 3, 8, 9],
       [7, 3, 3, 0, 6],
       [4, 0, 4, 2, 8]], dtype=int32)>

## 常用层
* tf.keras.layers
* tf.nn


In [18]:
a = tf.random.uniform(shape=(10,100,50), minval=-0.5, maxval=0.5)
x = tf.keras.layers.LSTM(100)(a)
x = tf.keras.layers.Dense(10)(x)
x = tf.nn.softmax(x)

增加层的参数配置

In [22]:
#层中增加激活函数
tf.keras.layers.Dense(64, activation='relu')
tf.keras.layers.Dense(64, activation=tf.nn.relu)
#L1正则应用于内核矩阵
tf.keras.layers.Dense(64, kernel_regularizer=tf.keras.regularizers.l1(0.01))
#L2正则应用于偏差向量
tf.keras.layers.Dense(64, bias_regularizer=tf.keras.regularizers.l1(0.01))
#内核初始化为随机正交矩阵的线性层
tf.keras.layers.Dense(64, kernel_initializer='orthogonal')
#偏差向量初始化为2.0的线性层
tf.keras.layers.Dense(64, bias_initializer=tf.keras.initializers.Constant(2.0))

# 三种建模方式

* Sequential model
* Functional model
* Subclassing model

tf.keras.Sequential

In [25]:
from tensorflow.keras import layers

model = tf.keras.Sequential()
model.add(layers.Dense(64, activation='relu'))

In [28]:
model = tf.keras.Sequential([
    layers.Dense(64, activation='relu'),
    layers.Dense(64, activation='relu'),
    layers.Dense(10)
])

In [30]:
model.compile(optimizer=tf.keras.optimizers.Adam(0.01),
             loss=tf.keras.losses.CategoricalCrossentropy(from_logits=True),
             metrics=['accuracy'])

In [31]:
import numpy as np
data = np.random.random((1000, 32))
labels = np.random.random((1000, 10))

model.fit(data, labels, epochs=10, batch_size=32)

Epoch 1/10
32/32 [==============================] - 0s 1ms/step - loss: 44.9186 - accuracy: 0.1060
Epoch 2/10
32/32 [==============================] - 0s 937us/step - loss: 244.2103 - accuracy: 0.1080
Epoch 3/10
32/32 [==============================] - 0s 950us/step - loss: 1434.8037 - accuracy: 0.1010
Epoch 4/10
32/32 [==============================] - 0s 891us/step - loss: 3062.5247 - accuracy: 0.1080
Epoch 5/10
32/32 [==============================] - 0s 923us/step - loss: 4571.5767 - accuracy: 0.1170
Epoch 6/10
32/32 [==============================] - 0s 863us/step - loss: 8570.4746 - accuracy: 0.1100
Epoch 7/10
32/32 [==============================] - 0s 853us/step - loss: 13375.3154 - accuracy: 0.0920
Epoch 8/10
32/32 [==============================] - 0s 884us/step - loss: 22187.5176 - accuracy: 0.0840
Epoch 9/10
32/32 [==============================] - 0s 868us/step - loss: 25929.4355 - accuracy: 0.0970
Epoch 10/10
32/32 [==============================] - 0s 927us/step - loss: 

Functional model

In [34]:
inputs = tf.keras.Input(shape=(32,))
x = layers.Dense(64, activation='relu')(inputs)
x = layers.Dense(64, activation='relu')(x)
predictions = layers.Dense(10)(x)

In [35]:
model = tf.keras.Model(inputs=inputs, outputs=predictions)
model.compile(optimizer=tf.keras.optimizers.RMSprop(0.001),
             loss=tf.keras.losses.CategoricalCrossentropy(from_logits=True),
             metrics=['accuracy'])

model.fit(data, labels, epochs=10, batch_size=32)

Epoch 1/10
32/32 [==============================] - 0s 1ms/step - loss: 12.6128 - accuracy: 0.1090
Epoch 2/10
32/32 [==============================] - 0s 1ms/step - loss: 18.0559 - accuracy: 0.1110
Epoch 3/10
32/32 [==============================] - 0s 1ms/step - loss: 29.9134 - accuracy: 0.1030
Epoch 4/10
32/32 [==============================] - 0s 886us/step - loss: 47.9776 - accuracy: 0.0980
Epoch 5/10
32/32 [==============================] - 0s 858us/step - loss: 70.1486 - accuracy: 0.1120
Epoch 6/10
32/32 [==============================] - 0s 816us/step - loss: 93.4897 - accuracy: 0.0990
Epoch 7/10
32/32 [==============================] - 0s 871us/step - loss: 109.0365 - accuracy: 0.1060
Epoch 8/10
32/32 [==============================] - 0s 839us/step - loss: 107.1740 - accuracy: 0.0920
Epoch 9/10
32/32 [==============================] - 0s 882us/step - loss: 111.2587 - accuracy: 0.1070
Epoch 10/10
32/32 [==============================] - 0s 884us/step - loss: 124.8696 - accuracy

In [36]:
inputs1 = tf.keras.Input(shape=(32,))
inputs2 = tf.keras.Input(shape=(32,))
x1 = layers.Dense(64, activation='relu')(inputs1)
x2 = layers.Dense(64, activation='relu')(inputs2)
x = tf.concat([x1,x2], axis=-1)
x = layers.Dense(64, activation='relu')(x)
predictions = layers.Dense(10)(x)

In [39]:
model = tf.keras.Model(inputs=[inputs1, inputs2], outputs=predictions)

model.compile(optimizer=tf.keras.optimizers.RMSprop(0.001),
             loss=tf.keras.losses.CategoricalCrossentropy(from_logits=True),
             metrics=['accuracy'])

import numpy as np
data1 = np.random.random((1000, 32))
data2 = np.random.random((1000, 32))
labels = np.random.random((1000, 10))
model.fit((data1,data2), labels, batch_size=32, epochs=5)

Epoch 1/5
32/32 [==============================] - 0s 1ms/step - loss: 17.0394 - accuracy: 0.1080
Epoch 2/5
32/32 [==============================] - 0s 1ms/step - loss: 34.5748 - accuracy: 0.1150
Epoch 3/5
32/32 [==============================] - 0s 1ms/step - loss: 61.6542 - accuracy: 0.0900
Epoch 4/5
32/32 [==============================] - 0s 1ms/step - loss: 85.2308 - accuracy: 0.1020
Epoch 5/5
32/32 [==============================] - 0s 983us/step - loss: 110.2317 - accuracy: 0.1060


## 子类化

In [40]:
class MyModel(tf.keras.Model):
    def __init__(self, num_classes=10):
        super(MyModel, self).__init__(name='my_model')
        self.num_classes = num_classes
        self.dense_1 = layers.Dense(32, activation='relu')
        self.dense_2 = layers.Dense(num_classes)
        
    def call(self, inputs):
        # define forward propagation
        x = self.dense_1(inputs)
        return self.dense_2(x)

In [41]:
model = MyModel(num_classes=10)

model.compile(optimizer=tf.keras.optimizers.RMSprop(0.001),
             loss=tf.keras.losses.CategoricalCrossentropy(from_logits=True),
             metrics=['accuracy'])

import numpy as np
data = np.random.random((1000, 32))
labels = np.random.random((1000, 10))
model.fit(data, labels, batch_size=32, epochs=5)

Epoch 1/5
32/32 [==============================] - 0s 859us/step - loss: 13.1753 - accuracy: 0.0990
Epoch 2/5
32/32 [==============================] - 0s 924us/step - loss: 16.2055 - accuracy: 0.1110
Epoch 3/5
32/32 [==============================] - 0s 1ms/step - loss: 19.4920 - accuracy: 0.1250
Epoch 4/5
32/32 [==============================] - 0s 1ms/step - loss: 22.5090 - accuracy: 0.1140
Epoch 5/5
32/32 [==============================] - 0s 1ms/step - loss: 25.5026 - accuracy: 0.1110
